object Versions {
    const val appCompat = "1.6.1"
    const val cicerone = "7.1"
    const val room = "2.5.0"
    const val dagger = "2.44.2"
    const val coroutines = "1.6.4"
    const val recyclerView = "1.2.1"
    const val lifecycle = "2.5.1"
    const val viewBinding = "1.5.6"
    const val yandexMap = "4.2.2-full"
    const val retrofit = "2.9.0"
    const val http = "4.10.0"
    const val coreKtx = "1.9.0"
    const val activityKtx = "1.6.1"
//    const val fragmentKtx = "1.5.5"
    const val espresso = "3.5.1"
const val material = "1.8.0"
const val jupiter = "5.8.2"
    const val mockk = "1.13.4"
    const val junitTest = "1.1.5"
    const val junit = "4.13.2"
    const val constraint = "2.1.4"
}